; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25831.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?multiply@@YAHHH@Z				; multiply
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?multiply@@YAHHH@Z DD imagerel $LN3
	DD	imagerel $LN3+65
	DD	imagerel $unwind$?multiply@@YAHHH@Z
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?multiply@@YAHHH@Z DD 05052a01H
	DD	01110314H
	DD	0700a0019H
	DD	05009H
xdata	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
a$ = 224
b$ = 232
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File f:\cpp\workspace\01_hello\01_hello\math.cpp
; Line 1
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rdi
	sub	rsp, 200				; 000000c8H
	mov	rbp, rsp
	mov	rdi, rsp
	mov	ecx, 50					; 00000032H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, DWORD PTR [rsp+232]
; Line 2
	mov	eax, DWORD PTR a$[rbp]
	imul	eax, DWORD PTR b$[rbp]
; Line 3
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
END
